FROM bash:5.2.26
RUN apk add curl
RUN wget -O '/bin/wait-for-it.sh' 'https://raw.githubusercontent.com/vishnubob/wait-for-it/81b1373f17855a4dc21156cfe1694c31d7d1792e/wait-for-it.sh'
RUN chmod +x /bin/wait-for-it.sh
